<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <CopyBuildOutputToPublishDirectory>false</CopyBuildOutputToPublishDirectory>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>

  <PropertyGroup>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>

  <ItemGroup Label="Remove BLOBs">
    <Compile Remove="**\*.cs" />
    <None Remove="ArvidsonFoto*\**\*.*" />
    <None Remove="SbomScanner\**\*.*" />
  </ItemGroup>

  <ItemGroup Label="Include BLOBs">
    <None Include=".config\**\*.*" />
    <None Include=".github\**\*.*" />
    <None Include="artifacts\**\*.*" />
    <None Include="TestResults\**\*.*" />
    <None Include="wiki\**\*.*" />
  </ItemGroup>

  <ItemGroup Label="Include BLOBs in ZIP">
    <MySolutionBlobs Include="$(SolutionDir)SharedConfigs\**\*.*" />
    <MySolutionBlobs Include="$(SolutionDir)DeployScripts\**\*.ps1" />
    <MySolutionBlobs Include="$(SolutionDir)global.json" />
    <MySolutionBlobs Include="$(SolutionDir)LICENSE" />
    <MySolutionBlobs Include="$(SolutionDir)README.md" />
  </ItemGroup>

  <Target Name="PackageSolutionBlobs" AfterTargets="Build">
    <PropertyGroup>
      <TargetBlobFolder>$(TargetDir)SolutionBlobs\</TargetBlobFolder>
    </PropertyGroup>

    <Message Importance="high" Text="--- Dynamic Blob Packaging Started ---" />

    <RemoveDir Directories="$(TargetBlobFolder)" Condition="Exists('$(TargetBlobFolder)')" />

    <Copy SourceFiles="@(MySolutionBlobs)" DestinationFiles="@(MySolutionBlobs->'$(TargetBlobFolder)%(RecursiveDir)%(Filename)%(Extension)')" />

    <ZipDirectory SourceDirectory="$(TargetBlobFolder)" DestinationFile="$(TargetDir)SolutionItems_Blob.zip" Overwrite="true" />

    <Message Importance="high" Text="--- Blob created successfully at: $(TargetDir)SolutionItems_Blob.zip ---" />
  </Target>

</Project>