// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace ArvidsonFoto.Core.Migrations.ArvidsonFotoIdentity;

/// <summary>
/// Entity Framework migrering: AddPasskeySupport
/// Lägger till AspNetUserPasskeys-tabellen för WebAuthn passkey-stöd (.NET 10 Identity v3).
/// </summary>
public partial class AddPasskeySupport : Migration
{
    /// <summary>
    /// Applicerar migreringen.
    /// </summary>
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "AspNetUserPasskeys",
            columns: table => new
            {
                CredentialId = table.Column<byte[]>(type: "varbinary(1024)", maxLength: 1024, nullable: false),
                UserId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                Data = table.Column<string>(type: "nvarchar(max)", nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_AspNetUserPasskeys", x => x.CredentialId);
                table.ForeignKey(
                    name: "FK_AspNetUserPasskeys_AspNetUsers_UserId",
                    column: x => x.UserId,
                    principalTable: "AspNetUsers",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
            });

        migrationBuilder.CreateIndex(
            name: "IX_AspNetUserPasskeys_UserId",
            table: "AspNetUserPasskeys",
            column: "UserId");
    }

    /// <summary>
    /// Återställer migreringen.
    /// </summary>
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "AspNetUserPasskeys");
    }
}
