// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace ArvidsonFoto.Core.Migrations
{
    /// <inheritdoc />
    public partial class AddEnglishColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Add English columns to tbl_gb (Guestbook)
            migrationBuilder.AddColumn<string>(
                name: "GB_name_EN",
                table: "tbl_gb",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "GB_text_EN",
                table: "tbl_gb",
                type: "nvarchar(max)",
                nullable: true);

            // Add English columns to tbl_menu (Menu categories)
            migrationBuilder.AddColumn<string>(
                name: "menu_text_EN",
                table: "tbl_menu",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "menu_URLtext_EN",
                table: "tbl_menu",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            // Add English columns to tbl_images (Images)
            migrationBuilder.AddColumn<string>(
                name: "image_description_EN",
                table: "tbl_images",
                type: "nvarchar(150)",
                maxLength: 150,
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Remove English columns from tbl_gb
            migrationBuilder.DropColumn(
                name: "GB_name_EN",
                table: "tbl_gb");

            migrationBuilder.DropColumn(
                name: "GB_text_EN",
                table: "tbl_gb");

            // Remove English columns from tbl_menu
            migrationBuilder.DropColumn(
                name: "menu_text_EN",
                table: "tbl_menu");

            migrationBuilder.DropColumn(
                name: "menu_URLtext_EN",
                table: "tbl_menu");

            // Remove English columns from tbl_images
            migrationBuilder.DropColumn(
                name: "image_description_EN",
                table: "tbl_images");
        }
    }
}
