// <auto-generated />
using System;
using ArvidsonFoto.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArvidsonFoto.Core.Migrations;

[DbContext(typeof(ArvidsonFotoCoreDbContext))]
partial class ArvidsonFotoDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260926105909_AddEnglishColumns";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .UseCollation("Finnish_Swedish_CI_AS")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("ArvidsonFoto.Core.Models.TblGb", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("ID");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<DateTime?>("GbDate")
                    .HasColumnType("smalldatetime")
                    .HasColumnName("GB_date");

                b.Property<string>("GbEmail")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)")
                    .HasColumnName("GB_email");

                b.Property<string>("GbHomepage")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)")
                    .HasColumnName("GB_homepage");

                b.Property<int>("GbId")
                    .HasColumnType("int")
                    .HasColumnName("GB_ID");

                b.Property<string>("GbIp")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("GB_IP");

                b.Property<string>("GbName")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)")
                    .HasColumnName("GB_name");

                b.Property<string>("GbNameEn")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)")
                    .HasColumnName("GB_name_en");

                b.Property<bool?>("GbReadPost")
                    .HasColumnType("bit")
                    .HasColumnName("GB_ReadPost");

                b.Property<string>("GbText")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("GB_text");

                b.Property<string>("GbTextEn")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("GB_text_en");

                b.HasKey("Id");

                b.ToTable("tbl_gb");
            });

        modelBuilder.Entity("ArvidsonFoto.Core.Models.TblImage", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("ID");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<int?>("ImageCategoryId")
                    .HasColumnType("int")
                    .HasColumnName("image_art");

                b.Property<DateTime?>("ImageDate")
                    .HasColumnType("smalldatetime")
                    .HasColumnName("image_date");

                b.Property<string>("ImageDescription")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)")
                    .HasColumnName("image_description");

                b.Property<string>("ImageDescriptionEn")
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)")
                    .HasColumnName("image_description_en");

                b.Property<int?>("ImageFamilyId")
                    .HasColumnType("int")
                    .HasColumnName("image_familj");

                b.Property<int?>("ImageId")
                    .HasColumnType("int")
                    .HasColumnName("image_ID");

                b.Property<int?>("ImageMainFamilyId")
                    .HasColumnType("int")
                    .HasColumnName("image_huvudfamilj");

                b.Property<DateTime?>("ImageUpdate")
                    .HasColumnType("datetime")
                    .HasColumnName("image_update");

                b.Property<string>("ImageUrlName")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("image_URL");

                b.HasKey("Id");

                b.ToTable("tbl_images");
            });

        modelBuilder.Entity("ArvidsonFoto.Core.Models.TblKontakt", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("ID");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)")
                    .HasColumnName("Email");

                b.Property<bool>("EmailSent")
                    .HasColumnType("bit")
                    .HasColumnName("EmailSent");

                b.Property<string>("ErrorMessage")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)")
                    .HasColumnName("ErrorMessage");

                b.Property<string>("Message")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)")
                    .HasColumnName("Message");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("Name");

                b.Property<string>("SourcePage")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("SourcePage");

                b.Property<string>("Subject")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("Subject");

                b.Property<DateTime>("SubmitDate")
                    .HasColumnType("datetime")
                    .HasColumnName("SubmitDate");

                b.HasKey("Id");

                b.ToTable("tbl_kontakt");
            });

        modelBuilder.Entity("ArvidsonFoto.Core.Models.TblMenu", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("ID");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<int?>("MenuCategoryId")
                    .HasColumnType("int")
                    .HasColumnName("menu_ID");

                b.Property<DateTime?>("MenuDateUpdated")
                    .HasColumnType("datetime")
                    .HasColumnName("menu_dateUpdated");

                b.Property<string>("MenuDisplayName")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("menu_text");

                b.Property<string>("MenuDisplayNameEn")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("menu_text_en");

                b.Property<int?>("MenuParentCategoryId")
                    .HasColumnType("int")
                    .HasColumnName("menu_mainID");

                b.Property<string>("MenuUrlSegment")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("menu_URLtext");

                b.Property<string>("MenuUrlSegmentEn")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("menu_URLtext_en");

                b.HasKey("Id");

                b.ToTable("tbl_menu");
            });

        modelBuilder.Entity("ArvidsonFoto.Core.Models.TblPageCounter", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("PageCounter_ID");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<int>("CategoryId")
                    .HasColumnType("int")
                    .HasColumnName("PageCounter_CategoryId");

                b.Property<DateTime>("LastShowDate")
                    .HasColumnType("datetime")
                    .HasColumnName("PageCounter_LastShowDate");

                b.Property<string>("MonthViewed")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)")
                    .HasColumnName("PageCounter_MonthViewed");

                b.Property<string>("PageName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("PageCounter_Name");

                b.Property<int>("PageViews")
                    .HasColumnType("int")
                    .HasColumnName("PageCounter_Views");

                b.Property<bool>("PicturePage")
                    .HasColumnType("bit")
                    .HasColumnName("PageCounter_PicturePage");

                b.HasKey("Id");

                b.ToTable("tbl_PageCounter");
            });
#pragma warning restore 612, 618
    }
}
