// <auto-generated />
using System;
using ArvidsonFoto.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArvidsonFoto.Core.Migrations
{
    [DbContext(typeof(ArvidsonFotoDbContext))]
    partial class ArvidsonFotoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Finnish_Swedish_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArvidsonFoto.Core.Models.TblGb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GbDate")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("GB_date");

                    b.Property<string>("GbEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("GB_email");

                    b.Property<string>("GbHomepage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GB_homepage");

                    b.Property<int>("GbId")
                        .HasColumnType("int")
                        .HasColumnName("GB_ID");

                    b.Property<string>("GbIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GB_IP");

                    b.Property<string>("GbName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("GB_name");

                    b.Property<bool?>("GbReadPost")
                        .HasColumnType("bit")
                        .HasColumnName("GB_ReadPost");

                    b.Property<string>("GbText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GB_text");

                    b.HasKey("Id");

                    b.ToTable("tbl_gb", (string)null);
                });

            modelBuilder.Entity("ArvidsonFoto.Core.Models.TblImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ImageCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("image_art");

                    b.Property<DateTime?>("ImageDate")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("image_date");

                    b.Property<string>("ImageDescription")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("image_description");

                    b.Property<int?>("ImageFamilyId")
                        .HasColumnType("int")
                        .HasColumnName("image_familj");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int")
                        .HasColumnName("image_ID");

                    b.Property<int?>("ImageMainFamilyId")
                        .HasColumnType("int")
                        .HasColumnName("image_huvudfamilj");

                    b.Property<DateTime?>("ImageUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("image_update");

                    b.Property<string>("ImageUrlName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("image_URL");

                    b.HasKey("Id");

                    b.ToTable("tbl_images", (string)null);
                });

            modelBuilder.Entity("ArvidsonFoto.Core.Models.TblMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MenuCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("menu_ID");

                    b.Property<string>("MenuDisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_text");

                    b.Property<int?>("MenuParentCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("menu_mainID");

                    b.Property<string>("MenuUrlSegment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_URLtext");

                    b.HasKey("Id");

                    b.ToTable("tbl_menu", (string)null);
                });

            modelBuilder.Entity("ArvidsonFoto.Core.Models.TblPageCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PageCounter_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("PageCounter_CategoryId");

                    b.Property<DateTime>("LastShowDate")
                        .HasColumnType("datetime")
                        .HasColumnName("PageCounter_LastShowDate");

                    b.Property<string>("MonthViewed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PageCounter_MonthViewed");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PageCounter_Name");

                    b.Property<int>("PageViews")
                        .HasColumnType("int")
                        .HasColumnName("PageCounter_Views");

                    b.Property<bool>("PicturePage")
                        .HasColumnType("bit")
                        .HasColumnName("PageCounter_PicturePage");

                    b.HasKey("Id");

                    b.ToTable("tbl_PageCounter", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
