// <auto-generated />
using System;
using ArvidsonFoto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArvidsonFoto.Migrations
{
    [DbContext(typeof(ArvidsonFotoDbContext))]
    [Migration("20210121114415_Skapar tabeller")]
    partial class Skapartabeller
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "Finnish_Swedish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ArvidsonFoto.Models.TblAdmin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_ID");

                    b.Property<DateTime?>("AdminLastonline")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("admin_lastonline");

                    b.Property<string>("AdminMail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("admin_mail");

                    b.Property<string>("AdminName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("admin_name");

                    b.Property<string>("AdminPass")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("admin_pass");

                    b.Property<string>("AdminUser")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("admin_user");

                    b.ToTable("tbl_admin");
                });

            modelBuilder.Entity("ArvidsonFoto.Models.TblGb", b =>
                {
                    b.Property<DateTime?>("GbDate")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("GB_date");

                    b.Property<string>("GbEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("GB_email");

                    b.Property<string>("GbHomepage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GB_homepage");

                    b.Property<int>("GbId")
                        .HasColumnType("int")
                        .HasColumnName("GB_ID");

                    b.Property<string>("GbIp")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GB_IP");

                    b.Property<string>("GbName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("GB_name");

                    b.Property<string>("GbText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GB_text");

                    b.ToTable("tbl_gb");
                });

            modelBuilder.Entity("ArvidsonFoto.Models.TblImage", b =>
                {
                    b.Property<int>("ImageArt")
                        .HasColumnType("int")
                        .HasColumnName("image_art");

                    b.Property<DateTime?>("ImageDate")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("image_date");

                    b.Property<string>("ImageDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("image_description");

                    b.Property<int?>("ImageFamilj")
                        .HasColumnType("int")
                        .HasColumnName("image_familj");

                    b.Property<int?>("ImageHuvudfamilj")
                        .HasColumnType("int")
                        .HasColumnName("image_huvudfamilj");

                    b.Property<int>("ImageId")
                        .HasColumnType("int")
                        .HasColumnName("image_ID");

                    b.Property<DateTime>("ImageUpdate")
                        .HasColumnType("datetime")
                        .HasColumnName("image_update");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("image_URL");

                    b.ToTable("tbl_images");
                });

            modelBuilder.Entity("ArvidsonFoto.Models.TblMenu", b =>
                {
                    b.Property<string>("MenuEngtext")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_ENGtext");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_ID");

                    b.Property<DateTime?>("MenuLastshowdate")
                        .HasColumnType("datetime")
                        .HasColumnName("menu_lastshowdate");

                    b.Property<short?>("MenuMainId")
                        .HasColumnType("smallint")
                        .HasColumnName("menu_mainID");

                    b.Property<int?>("MenuPagecounter")
                        .HasColumnType("int")
                        .HasColumnName("menu_pagecounter");

                    b.Property<string>("MenuText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_text");

                    b.Property<string>("MenuUrltext")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menu_URLtext");

                    b.ToTable("tbl_menu");
                });
#pragma warning restore 612, 618
        }
    }
}
