<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <Target Name="CopyLockFilesAndProps" AfterTargets="Build">
    <ItemGroup>
      <LockFiles Include="..\**\packages.lock.json" Exclude="..\SbomScanner\**\packages.lock.json" />
      <PropsFile Include="..\Directory.Packages.props" />
    </ItemGroup>

    <Copy SourceFiles="@(LockFiles)"
          DestinationFiles="@(LockFiles->'$(TargetDir)ProjectLockfiles\%(RecursiveDir)packages.lock.json')"
          SkipUnchangedFiles="true" />

    <Copy SourceFiles="@(PropsFile)"
          DestinationFolder="$(TargetDir)"
          SkipUnchangedFiles="true" />
  </Target>
  
</Project>
