<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <ItemGroup>
    <ProjectReference Include="..\ArvidsonFoto\ArvidsonFoto.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="MessagePack" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);ASPIRE010</NoWarn>
    <UserSecretsId>ArvidsonFoto-AppHost-327cb2dd-ebf6-45e3-af0f-e6311e932efe</UserSecretsId>
  </PropertyGroup>

</Project>
